# Curso: "El lenguaje de programación Python para la docencia en el ámbito científico"

&nbsp;  
<img src="../images/logo_python_letras.png" align="center" style="width:350px;"/>

<strong><div style="text-align: center"> [Mabel Delgado Babiano](https://es.linkedin.com/in/mabeldelgadob)</div></strong>

&nbsp;  
<div style="text-align: center">Heredia, Costa Rica</div>
<div style="text-align: center">4 - 7 Febrero 2019</div>


# NumPy: Álgebra Lineal

_Una vez hemos visto el manejo básico de arrays en Python con NumPy, es hora de pasar a operaciones más interesantes como son las propias del **Álgebra Lineal**._

_Los productos escalares y las inversiones de matrices están por todas partes en los programas científicos e ingenieriles, y en este notebook veremos cómo se hacen con Python._

 *¿Estás preparado/a? ¡¡Pues empezamos!!*

## Álgebra lineal

Como sabemos, las operaciones del álgebra lineal aparecen con mucha frecuencia a la hora de resolver sistemas de ecuaciones en derivadas parciales y en general al linealizar problemas de todo tipo, y suele ser necesario resolver sistemas con un número enorme de ecuaciones e incógnitas. Gracias a los arrays de NumPy podemos abordar este tipo de cálculos en Python, ya que todas las funciones están escritas en C o Fortran y tenemos la opción de usar bibliotecas optimizadas al límite.

El paquete de álgebra lineal en NumPy se llama `linalg`, así que importando NumPy con la convención habitual podemos acceder a él escribiendo `np.linalg`. Si imprimimos la ayuda del paquete vemos que tenemos funciones para:

* Funciones básicas (norma de un vector, inversa de una matriz, determinante, traza)
* Resolución de sistemas
* Autovalores y autovectores
* Descomposiciones matriciales (QR, SVD)
* Pseudoinversas

Puede que ya sepas que en la biblioteca `SciPy` se pueden encontrar también funciones de Álgebra Lineal. ¿Cuáles usar? Puedes encontrar la respuesta en este enlace: https://docs.scipy.org/doc/scipy-0.18.1/reference/tutorial/linalg.html#scipy-linalg-vs-numpy-linalg

Como de momento sólo hemos usado `NumPy` no importaremos las funciones de `SciPy`, aunque como ves, es recomendable hacerlo.

In [2]:
import numpy as np

In [3]:
# Accediendo a la ayuda
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

Recordemos que si queremos usar una función de un paquete pero no queremos escribir la "ruta" completa cada vez, podemos usar la sintaxis `from package import func`:

In [4]:
# Importando la norma y el determinante
from numpy.linalg import norm, det
norm

<function numpy.linalg.linalg.norm(x, ord=None, axis=None, keepdims=False)>

### Traspuesta

#### Arrays bidimensionales

In [4]:
M = np.array([
    [1, 2],
    [3, 4]
])
M

array([[1, 2],
       [3, 4]])

In [5]:
# Traspuesta de M
M.T

array([[1, 3],
       [2, 4]])

In [6]:
# o lo que es lo mismo
np.transpose(M)

array([[1, 3],
       [2, 4]])

#### Arrays unidimensionales

In [7]:
v = np.array([1, -1])
v

array([ 1, -1])

In [8]:
# Traspuesta de v
v.T

array([ 1, -1])

In [9]:
v.ndim

1

Como vemos, la traspuesta no funciona en los arrays unidimesionales. Esto se debe a que tienen `ndim=1`. Si queremos o necesitamos obtener un vector columna, es decir, de dos dimensiones, `ndim=2`, a partir de un array unidimensional, entonces hay que hacer lo siguiente:

In [10]:
# utilizar reshape en lugar de traspose
v_2dim = v.reshape((-1, 1))
v_2dim

array([[ 1],
       [-1]])

In [11]:
# o bien, utilizar expand_dim para pasar a ndim=2, y luego trasponer
v_2dim = np.expand_dims(v, axis=0)
v_2dim

array([[ 1, -1]])

In [12]:
v_2dim.T

array([[ 1],
       [-1]])

### Producto de una matriz por un vector

El producto matricial usual (no el que se hace elemento a elemento, sino el del álgebra lineal) se calcula con la misma función que el producto matriz-vector y el producto escalar vector-vector: con la función `dot`, que **no** está en el paquete `linalg` sino directamente en `numpy` y no hace falta importarlo.

In [13]:
np.dot

<function numpy.core.multiarray.dot>

Una consideración importante a tener en cuenta es que en NumPy no hace falta ser estricto a la hora de manejar vectores como si fueran matrices columna, siempre que la operación sea consistente. Un vector es una matriz con una sola dimensión: por eso si calculamos su traspuesta no funciona, como hemos visto anteriormente.

In [14]:
# Producto matriz vector
u = np.dot(M, v)
u

array([-1, -1])

<div class="alert alert-info">
 En la versión 3.5 de Python se incorporó un nuevo operador `@` para poder calcular hacer multiplicaciones de matrices de una forma más legible.
</div>

In [15]:
u = M @ v
u

array([-1, -1])

### Comparaciones entre arrays

Para hacer comparaciones entre arrays de punto flotante se pueden usar las funciones `np.allclose` y `np.isclose`. La primera comprueba si todos los elementos de los arrays son iguales dentro de una tolerancia, y la segunda compara elemento a elemento y devuelve un array de valores `True` y `False`.

In [16]:
u, v

(array([-1, -1]), array([ 1, -1]))

In [17]:
np.allclose(u, v)

False

In [18]:
np.isclose(0.0, 1e-8, atol=1e-10)

False

In [19]:
np.isclose(0.0, 1e-8, atol=1e-6)

True

### Producto, determinante, sistema de ecuaciones

#### Ejercicios

**1- Hallar el producto de estas dos matrices y su determinante:**

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

In [20]:
from numpy.linalg import det

In [21]:
A = np.array([
    [1, 0, 0],
    [2, 1, 1],
    [-1, 0, 1]
])
B = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])
print(A)
print(B)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]
[[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]


In [22]:
C = A @ B
C

array([[ 2,  3, -1],
       [ 4,  4,  2],
       [-2, -3,  4]])

In [23]:
det(C)

-12.0

**2- Resolver el siguiente sistema:**

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

In [24]:
M = (np.array([[2, 0, 0],
                [-1, 1, 0],
                [3, 2, -1]])
     @
        np.array([[1, 1, 1],
                        [0, 1, 2],
                        [0, 0, 1]]))
M

array([[ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  5,  6]])

In [25]:
# PISTA: busca dentro de linalg la función solve
x = np.linalg.solve(M, np.array([-1, 3, 0]))
x

array([ 0.5, -4.5,  3.5])

In [26]:
# comprobación
np.allclose(M @ x, np.array([-1, 3, 0]))

True

**3- Hallar la inversa de la matriz $H$ y comprobar que $H H^{-1} = I$ (recuerda la función `np.eye`)**

In [27]:
# preserve
A = np.arange(1, 37).reshape(6,6)
A[1, 1::2] = 0
A[3, ::2] = 1
A[4, :] += 30
B = (2 ** np.arange(36)).reshape((6,6))
H = A + B
print(H)

[[          2           4           7          12          21          38]
 [         71         128         265         512        1035        2048]
 [       4109        8206       16399       32784       65553      131090]
 [     262145      524308     1048577     2097174     4194305     8388632]
 [   16777271    33554488    67108921   134217786   268435515   536870972]
 [ 1073741855  2147483680  4294967329  8589934626 17179869219 34359738404]]


In [28]:
np.linalg.det(H)

-18849.027801318916

In [29]:
Hinv = np.linalg.inv(H)

In [30]:
np.isclose(np.dot(Hinv, H), np.eye(6))

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False,  True, False,  True],
       [ True, False,  True, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [31]:
print(np.dot(Hinv, H))

[[-3.00000000e+01 -6.00000000e+01 -1.28000000e+02 -2.40000000e+02
  -4.80000000e+02 -9.60000000e+02]
 [ 2.20000000e+01  4.00000000e+01  8.00000000e+01  1.60000000e+02
   3.20000000e+02  6.40000000e+02]
 [ 0.00000000e+00  0.00000000e+00 -1.60000000e+01  0.00000000e+00
  -6.40000000e+01  0.00000000e+00]
 [ 0.00000000e+00  4.00000000e+00  0.00000000e+00  1.60000000e+01
   3.20000000e+01  0.00000000e+00]
 [-2.22265625e+00  6.36718750e-01 -2.02343750e+00 -7.70312500e+00
   4.53125000e+00 -1.13125000e+01]
 [ 7.29492188e-01 -1.93359375e-01  2.37500000e+00 -7.03125000e-02
  -8.54687500e+00 -5.06250000e+00]]


<div class="alert alert-warning">¡No funciona! Y no solo eso sino que los resultados varían de un ordenador a otro.</div>

**4- Comprobar el número de condición de la matriz $H$.**

In [32]:
np.linalg.cond(H)

9.436622252881622e+16

<div class="alert alert-warning">La matriz está mal condicionada.</div>

### Autovalores y autovectores 

La cosa no queda ahí y también se pueden resolver problemas de autovalores y autovectores:

In [45]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 0, -1]
])

l, v = np.linalg.eig(A)
l, v

(array([ 4.31662479e+00, -2.31662479e+00,  1.47314580e-16]),
 array([[ 0.58428153,  0.73595785,  0.40824829],
        [ 0.80407569, -0.38198836, -0.81649658],
        [ 0.10989708, -0.55897311,  0.40824829]]))

In [50]:
np.isclose(A @ v[:, 0],  l[0] * v[:, 0])   #Av = lv

array([ True,  True,  True])

##### ¡Quiero más! Algunos enlaces interesantes...


* [Álgebra lineal en Python con NumPy en Pybonacci](http://pybonacci.org/2012/06/07/algebra-lineal-en-python-con-numpy-i-operaciones-basicas/)

--- 

__Referencias__

Material adaptado del "Curso AeroPython". AeroPython. https://github.com/AeroPython/Curso_AeroPython<br>

 <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.es"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Curso AeroPython</span> por <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Juan Luis Cano Rodriguez y Alejandro Sáez Mollejo</span> se distribuye bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.es">Licencia Creative Commons Atribución 4.0 Internacional</a>.

---
_Las siguientes celdas contienen configuración del Notebook_

_Para aplicarla el notebook debe ejecutarse como [seguro](http://ipython.org/ipython-doc/dev/notebook/security.html)_

    File > Trusted Notebook

In [1]:
# preserve
# Esta celda da el estilo al notebook
from IPython.core.display import HTML
css_file = '../styles/style.css'
HTML(open(css_file, "r").read())